// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koohctabvooadnlanwoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtvb2hjdGFidm9vYWRubGFud29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDk0NDAsImV4cCI6MjA2ODgyNTQ0MH0.48d7EV8WzOYqcKcNesMzLDY1LRgai0wCuhz-1G5gNF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});